// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwm-w2Fhtknq-K8Euu7sl_yfHR6_xEKP8',
    appId: '1:664999368815:web:34b25e22c67bedd2d9559a',
    messagingSenderId: '664999368815',
    projectId: 'authtutorial-b75d1',
    authDomain: 'authtutorial-b75d1.firebaseapp.com',
    storageBucket: 'authtutorial-b75d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGn_63zDqtMkVCf_sX-5tqKxeEJ8WwtRU',
    appId: '1:664999368815:android:48e329d16321f7cbd9559a',
    messagingSenderId: '664999368815',
    projectId: 'authtutorial-b75d1',
    storageBucket: 'authtutorial-b75d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpfLzAgP1Ya8IHCEALwQx3XOaN_d2rFY',
    appId: '1:664999368815:ios:43c4c39513159422d9559a',
    messagingSenderId: '664999368815',
    projectId: 'authtutorial-b75d1',
    storageBucket: 'authtutorial-b75d1.appspot.com',
    iosClientId: '664999368815-ao91oidoci1343rr389uag4aj06jvrmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMpfLzAgP1Ya8IHCEALwQx3XOaN_d2rFY',
    appId: '1:664999368815:ios:43c4c39513159422d9559a',
    messagingSenderId: '664999368815',
    projectId: 'authtutorial-b75d1',
    storageBucket: 'authtutorial-b75d1.appspot.com',
    iosClientId: '664999368815-ao91oidoci1343rr389uag4aj06jvrmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );
}
